--liquibase formatted sql
--changeset liquibase:create -multiple-tables:1 splitStatements:true endDelimiter:; context:dev
CREATE TABLE IF NOT EXISTS `testtype_version`
(
    `id`                                BIGINT AUTO_INCREMENT,
    `test_result_id`                    BIGINT,
    `vehicle_id`                        BIGINT,
    `fuel_emission_id`                  BIGINT,
    `test_station_id`                   BIGINT,
    `tester_id`                         BIGINT,
    `preparer_id`                       BIGINT,
    `vehicle_class_id`                  BIGINT,
    `test_type_id`                      BIGINT,
    `testStatus`                        VARCHAR(9),
    `reasonForCancellation`             VARCHAR(500),
    `numberOfSeats`                     INT(11),
    `odometerReading`                   INT(10),
    `odometerReadingUnits`              VARCHAR(10),
    `countryOfRegistration`             VARCHAR(56),
    `noOfAxles`                         TINYINT(3),
    `regnDate`                          DATE DEFAULT NULL,
    `firstUseDate`                      DATE DEFAULT NULL,
    `createdAt`                         DATETIME(6) DEFAULT NULL,
    `lastUpdatedAt`                     DATETIME(6) DEFAULT NULL,
    `testCode`                          VARCHAR(4),
    `testNumber`                        VARCHAR(45),
    `certificateNumber`                 VARCHAR(9),
    `secondaryCertificateNumber`        VARCHAR(9),
    `testExpiryDate`                    DATE,
    `testAnniversaryDate`               DATE,
    `testTypeStartTimestamp`            DATETIME,
    `testTypeEndTimestamp`              DATETIME,
    `numberOfSeatbeltsFitted`           TINYINT UNSIGNED,
    `lastSeatbeltInstallationCheckDate` DATE,
    `seatbeltInstallationCheckDate`     TINYINT(1),
    `testResult`                        VARCHAR(9),
    `reasonForAbandoning`               VARCHAR(45),
    `additionalNotesRecorded`           VARCHAR(500),
    `additionalCommentsForAbandon`      VARCHAR(500),
    `particulateTrapFitted`             VARCHAR(100),
    `particulateTrapSerialNumber`       VARCHAR(100),
    `modificationTypeUsed`              VARCHAR(100),
    `smokeTestKLimitApplied`            VARCHAR(100),
    `testType_insert_ts`                DATETIME DEFAULT NOW(),
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB;